Updated Harmony Guide to make it more clearer for new comers
NuclearPowered/docs.reactor.gg pull request #2
Opened 2021-03-10 08:34 UTC by apollyon600

2021-03-10 09:11 UTC, js6pak requested changes

2021-03-10 09:11 UTC, js6pak commented on docs/basic/harmony_guide.md
> +## Running 4 instances with just 2 clicks
Windows only and its looking sus in general

2021-03-10 09:11 UTC, js6pak commented on docs/basic/harmony_guide.md
> +Click this link: https://github.com/NuclearPowered/Reactor/suites/2107184644/artifacts/42856716
This is a direct link that will get outdated, nightly.link is a cool alternative https://nightly.link/NuclearPowered/Reactor/workflows/main/master/Reactor.Debugger.dll

2021-03-10 09:14 UTC, apollyon600 commented on docs/basic/harmony_guide.md
> +## Running 4 instances with just 2 clicks
you're sus

2021-03-10 09:20 UTC, apollyon600 commented
Updated @js6pak

2021-03-10 10:10 UTC, js6pak commented
Debugging isn't windows only, "Running 4 instances with just 2 clicks" bat thing is

2021-03-10 10:13 UTC, apollyon600 commented
> Debugging isn't windows only, "Running 4 instances with just 2 clicks" bat thing is

Well, I assumed you meant the path was for windows only.

2021-03-12 22:14 UTC, apollyon600 commented
anything else needed?

2021-03-15 22:28 UTC, merged